### ISSUE TITLE
Binding does not switch presets but instead reloads all presets

### ISSUE THREAD

**Issue by aboode95** [Mrcubix/Preset.Binding#3]
I have 2 presets ("absolute_mine" and "artist"). I bind 2 tablet button to each of the presets (Auxiliary binding 1: "Preset:(Selected: absolute_mine)"; Auxiliary binding 2: "Preset:(Selected: artist)"). And applied and saved the modification.

But pressing the tablet button does not switch the preset but instead reloads both the presets.

What could be the cause for this? Is there a way to fix this?

I am attaching screenshot of the output from the console (P.S. I am not sure if the "Aggregate Exception" error is relevant to this problem I am facing. In the screenshot you can see that upon pressing the button, both the presets are reloaded.)

![Screenshot From 2024-11-12 11-40-46](https://github.com/user-attachments/assets/58323357-18a3-4410-8b15-3f017a974aaf)

![Screenshot From 2024-11-12 11-36-55](https://github.com/user-attachments/assets/31bd0f44-65c6-4775-9b29-06a070c7d4ee)

## System Info
OS: NixOS (Wayland)
OpenTabletDriver version: 0.6.4.0

**Comment by Mrcubix** [comment]
OTD's UX basicaly does the same thing as i, so if my plugin doesn't work, the UX is also supposed to fail.

**Comment by Mrcubix** [comment]
You may try to run the daemon manually in your terminal (not the service) and see if you can get more complete stacktrace from the daemon's side.

The exception moght not be hapmening on my side, as another kind of message would be expected.

**Comment by Mrcubix** [comment]
[Preset.Binding.zip](https://github.com/user-attachments/files/17719264/Preset.Binding.zip)

This build may give us some idea of what's going on

**Comment by Mrcubix** [comment]
No responses in more than 3 weeks
